apiVersion: v2
name: trustification
description: A Helm chart for managing Trustification services on Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: guac
  version: "0.1.x"
  repository: "https://kusaridev.github.io/helm-charts"
- name: grafana
  version: "6.57.4"
  repository: "https://grafana.github.io/helm-charts"
