{{ if .Values.createRoutes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: exhort-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
  name: exhort-api
spec:
  host: "exhort.{{ .Values.domain }}"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 8080
  to:
    kind: Service
    name: exhort-api
    weight: 100
  wildcardPolicy: None
{{ end }}
