{
 "title": "Trustification SLO",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Percentage of VEX documents that failed to index successfully",
   "type": "timeseries",
   "description": "Percentage of VEX documents that failed to index successfully (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by(namespace) (rate(index_failed_total{pod =~ \"vexination-indexer.*\"}[10m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"vexination-indexer.*\"}[10m]))) OR on () vector(0)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Percentage of SBOM documents that failed to index successfully",
   "type": "timeseries",
   "description": "Percentage of SBOM documents that failed to index successfully (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by(namespace) (rate(index_failed_total{pod =~ \"bombastic-indexer.*\"}[10m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"bombastic-indexer.*\"}[10m]))) OR on () vector(0)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Percentage of requests that failed (status code = 5xx)",
   "type": "timeseries",
   "description": "Percentage of requests that failed (status code = 5xx) (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by(namespace) (rate(bombastic_api_http_requests_total{status =~ \"5[0-9]+\"}[10m]))) / (sum by(namespace) (rate(bombastic_api_http_requests_total{status !~ \"5[0-9]+\"}[10m]))) OR on () vector(0)",
     "legendFormat": "bombastic {{namespace}}"
    },
    {
     "expr": "100 * (sum by(namespace) (rate(vexination_api_http_requests_total{status =~ \"5[0-9]+\"}[10m]))) / (sum by(namespace) (rate(vexination_api_http_requests_total{status !~ \"5[0-9]+\"}[10m]))) OR on () vector(0)",
     "legendFormat": "vexination {{namespace}}"
    },
    {
     "expr": "100 * (sum by(namespace) (rate(spog_api_http_requests_total{status =~ \"5[0-9]+\"}[10m]))) / (sum by(namespace) (rate(spog_api_http_requests_total{status !~ \"5[0-9]+\"}[10m]))) OR on () vector(0)",
     "legendFormat": "spog {{namespace}}"
    }
   ]
  },
  {
   "title": "Percentage of the search request response times below 1s",
   "type": "timeseries",
   "description": "Percentage of the search request response times below 1s (Higher is better).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * sum(rate(bombastic_api_http_requests_duration_seconds_bucket{exported_endpoint=\"/api/v1/sbom/search\", le=\"1\"}[10m])) by (namespace) / sum(rate(bombastic_api_http_requests_duration_seconds_count{exported_endpoint=\"/api/v1/sbom/search\"}[10m])) by (namespace))",
     "legendFormat": "bombastic ({{namespace}})"
    },
    {
     "expr": "(100 * sum(rate(vexination_api_http_requests_duration_seconds_bucket{exported_endpoint=\"/api/v1/vex/search\", le=\"1\"}[10m])) by (namespace) / sum(rate(vexination_api_http_requests_duration_seconds_count{exported_endpoint=\"/api/v1/vex/search\"}[10m])) by (namespace))",
     "legendFormat": "vexination ({{namespace}})"
    },
    {
     "expr": "(100 * sum(rate(spog_api_http_requests_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*/search\", le=\"1\"}[10m])) by (namespace) / sum(rate(spog_api_http_requests_duration_seconds_count{exported_endpoint=~\"/api/v1/.*/search\"}[10m])) by (namespace))",
     "legendFormat": "spog ({{namespace}})"
    }
   ]
  }
 ]
}