{
 "title": "Trustification",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Bombastic API Errors",
   "type": "timeseries",
   "description": "Rate of errors for Bombastic API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(bombastic_api_http_requests_total{status!~\"200|201\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "VEX indexing failures",
   "type": "timeseries",
   "description": "Number of SBOMs that failed to index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "eventbus_sent_total{pod=~\"vexination-indexer.*\", topic=~\"vex-failed.*\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Vexination API Errors",
   "type": "timeseries",
   "description": "Rate of errors for Vexination API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(vexination_api_http_requests_total{status!~\"200|201\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "SBOM indexing failures",
   "type": "timeseries",
   "description": "Number of SBOMs that failed to index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "eventbus_sent_total{pod=~\"bombastic-indexer.*\", topic=\"sbom-failed.*\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Spog API Errors",
   "type": "timeseries",
   "description": "Rate of errors for Spog API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(spog_api_http_requests_total{status!~\"200|201\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Bombastic Indexing Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(index_indexed_total{pod=~\"bombastic-indexer.*\"}[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Bombastic API request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(bombastic_api_http_requests_total[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Vexination Indexing Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(index_indexed_total{pod=~\"vexination-indexer.*\"}[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Vexination API request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(vexination_api_http_requests_total[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}