{
 "title": "Trustification Performance",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "SPOG API request latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(spog_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "SPOG API request throughput (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(spog_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Bombastic API request latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(bombastic_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Bombastic API request throughput (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(bombastic_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Vexination API request latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vexination_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Vexination API request throughput (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(vexination_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": " Bombastic Indexing Throughput (documents/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"bombastic-indexer.*\"}[10m]))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Vexination Indexing Throughput (document/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"vexination-indexer.*\"}[10m]))",
     "legendFormat": "$namespace"
    }
   ]
  }
 ]
}