apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: vexination-indexer
    app.kubernetes.io/component: indexer
    app.kubernetes.io/part-of: vexination
  name: vexination-indexer-monitor
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: infra
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: vexination-indexer
      app.kubernetes.io/component: indexer
      app.kubernetes.io/part-of: vexination
