apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: grafana
  name: grafana
spec:
  host: "grafana.{{ .Values.domain }}"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: service
  to:
    kind: Service
    name: trustification-grafana
    weight: 100
  wildcardPolicy: None
