apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: bombastic-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: bombastic
  name: bombastic-api-monitor
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: infra
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: bombastic-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: bombastic
